# Generated by Django 3.2.24 on 2024-02-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesModel',
            fields=[
                ('id', models.AutoField(
                    help_text='A unique identifier for each movie',
                    primary_key=True,
                    serialize=False
                )),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('rated', models.CharField(blank=True, max_length=10, null=True)),
                ('released', models.DateField(blank=True, null=True)),
                ('runtime', models.CharField(blank=True, max_length=10, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('writer', models.CharField(blank=True, max_length=255, null=True)),
                ('actors', models.CharField(blank=True, max_length=255, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('awards', models.CharField(blank=True, max_length=255, null=True)),
                ('poster', models.URLField(blank=True, null=True)),
                ('metascore', models.IntegerField(blank=True, null=True)),
                ('imdb_rating', models.DecimalField(
                    blank=True,
                    decimal_places=1,
                    max_digits=3,
                    null=True
                )),
                ('imdb_votes', models.FloatField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('dvd', models.DateField(blank=True, null=True)),
                ('box_office', models.CharField(blank=True, max_length=20, null=True)),
                ('production', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('response', models.BooleanField(default=False)),
            ],
        ),
    ]
